version: "3.1" 
services:
  mbsync:
    image: thehelpfulidiot/mbsync:latest
    container_name: mbsync
    volumes:
      - /path/to/mail:/mail
    environment:
      - host_name=server
      - port=port
      - remote_username=username
      - remote_password=password
      - ssltype=IMAPS
      - sslversions=TLSv1.2
      - mailbox_name=gmail
      - pipeline_depth=1024 #default=1024 but may need to be changed for some mail providers (https://manpages.debian.org/unstable/isync/mbsync.1.en.html#PipelineDepth)
      - PUID=1000
      - cron=yes
